<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>certifiction_biz_m</name>
   <tag></tag>
   <elementGuidId>7e2647b5-2910-4e6e-ba68-44cd41907711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-body1.css-ri9wdm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e9dcd3b6-1ffb-434a-9bab-f9f0f11f82d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body1 css-ri9wdm</value>
      <webElementGuid>9f957996-8163-4a37-8507-e61318ddd314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>기업용 월간 이용</value>
      <webElementGuid>5f90be3e-87c5-4a5f-9318-00e152ca360e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-1ixckvq&quot;]/main[@class=&quot;MuiBox-root css-1lscubz&quot;]/div[@class=&quot;MuiBox-root css-5094bx&quot;]/div[@class=&quot;MuiBox-root css-14f6zur&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-body1 css-ri9wdm&quot;]</value>
      <webElementGuid>0c1e99d6-cbb3-4876-bbf7-f6f4ca25bbfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div/div[2]/p</value>
      <webElementGuid>691edecc-1856-4e63-8314-71d65dc834b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='구성원 수'])[1]/following::p[1]</value>
      <webElementGuid>0788fad5-501a-47f8-9458-ca6ef9c24a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='조직 이름'])[1]/following::p[1]</value>
      <webElementGuid>c7d186ad-ad44-45d9-afbb-406aea9eac14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='월간 이용']/parent::*</value>
      <webElementGuid>7cd7d1b1-6940-4a59-a314-6c6511bcf8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>5cb6383f-6611-4417-8dfc-d7dc129eebd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '기업용 월간 이용' or . = '기업용 월간 이용')]</value>
      <webElementGuid>a3f13d71-bf7d-421f-afd5-61a42639c14d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
