<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nodata_Trashbin</name>
   <tag></tag>
   <elementGuidId>bc55561b-8bff-45df-89a6-ba0f9bc7f961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/main/div[3]/div/div/div[2]/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.MuiTypography-root.MuiTypography-h2.css-6w5kag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>f20e93b3-e4ba-4925-a770-be25680cf036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h2 css-6w5kag</value>
      <webElementGuid>c059f47b-33da-475a-a8b8-03bcb754bb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>항목 없음</value>
      <webElementGuid>39a4600e-1583-4855-a3da-70f8fd2cdbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-1ixckvq&quot;]/main[@class=&quot;MuiBox-root css-1lscubz&quot;]/div[@class=&quot;drag-container MuiBox-root css-p8o0fd&quot;]/div[@class=&quot;MuiBox-root css-18174ce&quot;]/div[@class=&quot;MuiBox-root css-15u9pkf&quot;]/div[@class=&quot;MuiBox-root css-0&quot;]/h2[@class=&quot;MuiTypography-root MuiTypography-h2 css-6w5kag&quot;]</value>
      <webElementGuid>70ebe17f-9250-4806-b4ef-1ebba5262c3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/main/div[3]/div/div/div[2]/h2</value>
      <webElementGuid>61140a8f-a7f6-4f29-b2b5-1ac23c6d7350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='휴지통에 있는 항목은 30일 후 완전히 삭제됩니다.'])[1]/following::h2[1]</value>
      <webElementGuid>46c7f3b9-9125-4136-9c5e-6272d59bf735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='휴지통 비우기'])[1]/following::h2[1]</value>
      <webElementGuid>da508154-f8f5-4c2e-a4ac-d555fd981d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='홈'])[1]/preceding::h2[1]</value>
      <webElementGuid>3d5a63b5-1891-4bb6-b9db-40bd44be8fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='문서 만들기'])[1]/preceding::h2[1]</value>
      <webElementGuid>4f9cddc4-ec6c-414b-83a5-409ea4a63553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='항목 없음']/parent::*</value>
      <webElementGuid>3e090fe9-d037-4727-a803-4fe61b2fe68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>c9a9a917-1265-4f91-b20b-90ae5fe7915c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = '항목 없음' or . = '항목 없음')]</value>
      <webElementGuid>a5e64619-6a6a-441c-a0a2-69f4b7e385f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
