<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Profile_icon</name>
   <tag></tag>
   <elementGuidId>81d81a5d-bb71-4b3c-8af5-5a7df9d69b55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.MuiAvatar-img.css-1hy9t21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/header/div/div/div[3]/button[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0046cbb2-0918-45c3-aa6b-a687749a6e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://www.hancomdocs.com/2cc34607-d24e-43aa-a2d6-7b3245284d4e</value>
      <webElementGuid>98964d59-d49e-4d2a-b0aa-89dd5627648e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAvatar-img css-1hy9t21</value>
      <webElementGuid>42244701-1ba0-4b11-b43c-20830e4e6373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;MuiBox-root css-1ixckvq&quot;]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionFixed mui-fixed css-ov9fzc&quot;]/div[@class=&quot;MuiToolbar-root MuiToolbar-dense css-1lljh5p&quot;]/div[@class=&quot;MuiBox-root css-oajpp9&quot;]/div[@class=&quot;MuiBox-root css-140v1mh&quot;]/button[@class=&quot;MuiButtonBase-root MuiIconButton-root MuiIconButton-sizeMedium css-90g4ls&quot;]/div[@class=&quot;MuiBox-root css-1hx2wa1&quot;]/div[@class=&quot;MuiAvatar-root MuiAvatar-circular css-qn1cgr&quot;]/img[@class=&quot;MuiAvatar-img css-1hy9t21&quot;]</value>
      <webElementGuid>6b57603f-5b6e-4bd5-892d-c35b919acb55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/div/div/div[3]/button[3]/div/div/img</value>
      <webElementGuid>7403fdcd-9766-4c99-9bc7-d07f8b82281a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'blob:https://www.hancomdocs.com/2cc34607-d24e-43aa-a2d6-7b3245284d4e')]</value>
      <webElementGuid>36d1e795-5187-464c-a1af-0e461b35870b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>fdb4b019-5377-4ca5-9d92-e6872bfadf9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'blob:https://www.hancomdocs.com/2cc34607-d24e-43aa-a2d6-7b3245284d4e']</value>
      <webElementGuid>0e43c77b-f055-44c5-a19c-23bd92b48274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
